name: TypeScript Type Check

on:
  pull_request:
    branches: [ main ] # Adjust if your main branch has a different name

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Using a recent LTS version

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript type check
        run: npm run type-check
